on:
  push:
    branches:
      - main

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Deps
        run: yarn

      - name: Install Deps
        run: yarn build

      # - name: Test Project
      #   run: 'pnpm test:unit'